import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import entriesRouter from "./entries";
import logItemsRouter from "./log_items";
import reportsRouter from "./reports";
import risksRouter from "./risks";
import networkRouter from "./network";
import afterActionRouter from "./after_action";
import dashboardRouter from "./dashboard";
import exportRouter from "./export";
import statusReportRouter from "./status_report";
import quotesRouter from "./quotes";
import zendeskRouter from "./zendesk";
import processesRouter from "./processes";
import projectsRouter from "./projects";
import strategicObjectivesRouter from "./strategic_objectives";
import azureVmsRouter from "./azure_vms";
import azureResourcesRouter from "./azure_resources";
import analyticsRouter from "./analytics";
import aiKnowledgeRouter from "./ai_knowledge";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/entries", entriesRouter);
router.use("/log-items", logItemsRouter);
router.use("/reports", reportsRouter);
router.use("/risks", risksRouter);
router.use("/network", networkRouter);
router.use("/after-action", afterActionRouter);
router.use("/dashboard", dashboardRouter);
router.use("/export", exportRouter);
router.use("/status-report", statusReportRouter);
router.use("/quotes", quotesRouter);
router.use("/zendesk", zendeskRouter);
router.use("/processes", processesRouter);
router.use("/projects", projectsRouter);
router.use("/strategic-objectives", strategicObjectivesRouter);
router.use("/azure-vms", azureVmsRouter);
router.use("/azure-resources", azureResourcesRouter);
router.use("/analytics", analyticsRouter);
router.use("/ai-knowledge", aiKnowledgeRouter);

export default router;
