import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Laptop } from "lucide-react";
import { ScriptOutput, psQuote } from "./script-output";

type IpMode = "dhcp" | "static";

function sanitizePrefix(value: string): number {
  const n = parseInt(value, 10);
  if (!Number.isFinite(n) || n < 1 || n > 32) return 24;
  return n;
}

function buildScript(f: {
  computerName: string;
  joinDomain: boolean;
  domain: string;
  ipMode: IpMode;
  ip: string;
  prefix: string;
  gateway: string;
  dns: string;
  enableRdp: boolean;
  restart: boolean;
}): string {
  const lines: string[] = [
    "# Add Laptop to Network & Configure - generated by SCCC IT Reporting",
    "# Run in an elevated PowerShell (Run as Administrator) on the new machine.",
    "",
    `$ErrorActionPreference = 'Stop'`,
    "",
    "try {",
  ];

  if (f.computerName) {
    lines.push(
      `    Write-Host 'Renaming computer...' -ForegroundColor Cyan`,
      `    Rename-Computer -NewName '${psQuote(f.computerName)}' -Force`,
      "",
    );
  }

  if (f.ipMode === "static") {
    lines.push(
      `    Write-Host 'Configuring static IP...' -ForegroundColor Cyan`,
      `    $adapter = Get-NetAdapter -Physical | Where-Object Status -eq 'Up' | Select-Object -First 1`,
      `    Remove-NetIPAddress -InterfaceIndex $adapter.ifIndex -Confirm:$false -ErrorAction SilentlyContinue`,
      `    New-NetIPAddress -InterfaceIndex $adapter.ifIndex -IPAddress '${psQuote(f.ip)}' -PrefixLength ${sanitizePrefix(
        f.prefix,
      )} -DefaultGateway '${psQuote(f.gateway)}'`,
    );
    if (f.dns) {
      const servers = f.dns
        .split(",")
        .map((s) => `'${psQuote(s.trim())}'`)
        .filter((s) => s !== "''")
        .join(", ");
      lines.push(`    Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses ${servers}`);
    }
    lines.push("");
  } else {
    lines.push(
      `    Write-Host 'Setting adapter to DHCP...' -ForegroundColor Cyan`,
      `    $adapter = Get-NetAdapter -Physical | Where-Object Status -eq 'Up' | Select-Object -First 1`,
      `    Set-NetIPInterface -InterfaceIndex $adapter.ifIndex -Dhcp Enabled`,
      `    Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses`,
      "",
    );
  }

  if (f.enableRdp) {
    lines.push(
      `    Write-Host 'Enabling Remote Desktop...' -ForegroundColor Cyan`,
      `    Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' -Name 'fDenyTSConnections' -Value 0`,
      `    Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'`,
      "",
    );
  }

  if (f.joinDomain && f.domain) {
    lines.push(
      `    Write-Host 'Joining domain ${psQuote(f.domain)} (you will be prompted for domain credentials)...' -ForegroundColor Cyan`,
      `    $cred = Get-Credential -Message 'Enter domain-join credentials'`,
      `    Add-Computer -DomainName '${psQuote(f.domain)}' -Credential $cred -Force`,
      "",
    );
  }

  lines.push(`    Write-Host 'Configuration complete.' -ForegroundColor Green`);

  if (f.restart) {
    lines.push(`    Write-Host 'Restarting in 5 seconds...' -ForegroundColor Yellow`, `    Start-Sleep -Seconds 5`, `    Restart-Computer -Force`);
  } else {
    lines.push(`    Write-Host 'A restart is required to apply the rename/domain join.' -ForegroundColor Yellow`);
  }

  lines.push("} catch {", `    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red`, "}", "");

  return lines.join("\n");
}

export function AddLaptopTool() {
  const [computerName, setComputerName] = useState("");
  const [joinDomain, setJoinDomain] = useState(true);
  const [domain, setDomain] = useState("");
  const [ipMode, setIpMode] = useState<IpMode>("dhcp");
  const [ip, setIp] = useState("");
  const [prefix, setPrefix] = useState("24");
  const [gateway, setGateway] = useState("");
  const [dns, setDns] = useState("");
  const [enableRdp, setEnableRdp] = useState(false);
  const [restart, setRestart] = useState(true);
  const [script, setScript] = useState<string | null>(null);

  const canGenerate =
    (computerName.trim() || (joinDomain && domain.trim()) || ipMode === "static") &&
    (!joinDomain || domain.trim()) &&
    (ipMode !== "static" || (ip.trim() && gateway.trim()));

  const handleGenerate = () => {
    setScript(
      buildScript({
        computerName: computerName.trim(),
        joinDomain,
        domain: domain.trim(),
        ipMode,
        ip: ip.trim(),
        prefix: prefix.trim(),
        gateway: gateway.trim(),
        dns: dns.trim(),
        enableRdp,
        restart,
      }),
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Laptop className="h-5 w-5" /> Add a laptop to the network
        </CardTitle>
        <CardDescription>
          Choose the steps to run, then generate a PowerShell script for the new machine: rename,
          IP configuration, Remote Desktop, and domain join.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-5">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1">
            <Label htmlFor="lp-name">New computer name</Label>
            <Input id="lp-name" placeholder="SCCC-LT-042" value={computerName} onChange={(e) => setComputerName(e.target.value)} />
          </div>
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2">
            <Checkbox id="lp-join" checked={joinDomain} onCheckedChange={(c) => setJoinDomain(!!c)} />
            <Label htmlFor="lp-join" className="cursor-pointer">Join Active Directory domain</Label>
          </div>
          {joinDomain && (
            <div className="space-y-1">
              <Label htmlFor="lp-domain">Domain name</Label>
              <Input id="lp-domain" placeholder="sccc.edu" value={domain} onChange={(e) => setDomain(e.target.value)} />
              <p className="text-xs text-muted-foreground">The script prompts for domain-join credentials at runtime — they are never stored.</p>
            </div>
          )}
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <Label>IP configuration</Label>
          <div className="flex gap-4 text-sm">
            <label className="flex cursor-pointer items-center gap-2">
              <input type="radio" checked={ipMode === "dhcp"} onChange={() => setIpMode("dhcp")} /> DHCP (automatic)
            </label>
            <label className="flex cursor-pointer items-center gap-2">
              <input type="radio" checked={ipMode === "static"} onChange={() => setIpMode("static")} /> Static
            </label>
          </div>
          {ipMode === "static" && (
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <Label htmlFor="lp-ip">IP address</Label>
                <Input id="lp-ip" placeholder="10.0.5.42" value={ip} onChange={(e) => setIp(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="lp-prefix">Subnet prefix length (1–32)</Label>
                <Input id="lp-prefix" type="number" min={1} max={32} placeholder="24" value={prefix} onChange={(e) => setPrefix(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="lp-gw">Default gateway</Label>
                <Input id="lp-gw" placeholder="10.0.5.1" value={gateway} onChange={(e) => setGateway(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="lp-dns">DNS servers (comma-separated)</Label>
                <Input id="lp-dns" placeholder="10.0.0.10, 10.0.0.11" value={dns} onChange={(e) => setDns(e.target.value)} />
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-wrap gap-6">
          <div className="flex items-center gap-2">
            <Checkbox id="lp-rdp" checked={enableRdp} onCheckedChange={(c) => setEnableRdp(!!c)} />
            <Label htmlFor="lp-rdp" className="cursor-pointer">Enable Remote Desktop</Label>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox id="lp-restart" checked={restart} onCheckedChange={(c) => setRestart(!!c)} />
            <Label htmlFor="lp-restart" className="cursor-pointer">Restart when finished</Label>
          </div>
        </div>

        <Button type="button" onClick={handleGenerate} disabled={!canGenerate}>
          Generate script
        </Button>
        {script && <ScriptOutput script={script} fileName="add-laptop.ps1" />}
      </CardContent>
    </Card>
  );
}
