import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Printer } from "lucide-react";
import { ScriptOutput, psQuote } from "./script-output";

function buildScript(f: {
  name: string;
  ip: string;
  driver: string;
  location: string;
  comment: string;
}): string {
  return `# Network Printer Installer - generated by SCCC IT Reporting
# Run in an elevated PowerShell (Run as Administrator) on the target Windows PC.

$PrinterName = '${psQuote(f.name)}'
$PrinterIP   = '${psQuote(f.ip)}'
$PortName    = "IP_$PrinterIP"
$DriverName  = '${psQuote(f.driver)}'
$Location    = '${psQuote(f.location)}'
$Comment     = '${psQuote(f.comment)}'

try {
    if ((Get-Service spooler).Status -ne 'Running') {
        Start-Service spooler
    }

    if (-not (Get-PrinterPort -Name $PortName -ErrorAction SilentlyContinue)) {
        Add-PrinterPort -Name $PortName -PrinterHostAddress $PrinterIP
    }

    if (-not (Get-Printer -Name $PrinterName -ErrorAction SilentlyContinue)) {
        Add-Printer -Name $PrinterName \`
                    -DriverName $DriverName \`
                    -PortName $PortName \`
                    -Location $Location \`
                    -Comment $Comment
    }

    Restart-Service -Name spooler -Force
    Start-Sleep -Seconds 2

    if (Get-Printer -Name $PrinterName -ErrorAction SilentlyContinue) {
        Write-Host "Printer '$PrinterName' installed successfully." -ForegroundColor Green
    } else {
        Write-Host "Printer '$PrinterName' not found after setup." -ForegroundColor Red
    }
} catch {
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
}
`;
}

export function InstallPrinterTool() {
  const [name, setName] = useState("");
  const [ip, setIp] = useState("");
  const [driver, setDriver] = useState("");
  const [location, setLocation] = useState("");
  const [comment, setComment] = useState("");
  const [script, setScript] = useState<string | null>(null);

  const canGenerate = name.trim() && ip.trim() && driver.trim();

  const handleGenerate = () => {
    setScript(
      buildScript({
        name: name.trim(),
        ip: ip.trim(),
        driver: driver.trim(),
        location: location.trim(),
        comment: comment.trim(),
      }),
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Printer className="h-5 w-5" /> Install a network printer
        </CardTitle>
        <CardDescription>
          Enter the printer details, then generate a PowerShell script to run on the target
          Windows PC. It creates the TCP/IP port and adds the printer to the print spooler.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1">
            <Label htmlFor="pr-name">Printer name</Label>
            <Input id="pr-name" placeholder="Front Office HP" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="space-y-1">
            <Label htmlFor="pr-ip">Printer IP address</Label>
            <Input id="pr-ip" placeholder="10.0.5.42" value={ip} onChange={(e) => setIp(e.target.value)} />
          </div>
          <div className="space-y-1">
            <Label htmlFor="pr-driver">Driver name (exact)</Label>
            <Input id="pr-driver" placeholder="HP Universal Printing PCL 6" value={driver} onChange={(e) => setDriver(e.target.value)} />
          </div>
          <div className="space-y-1">
            <Label htmlFor="pr-loc">Location</Label>
            <Input id="pr-loc" placeholder="Building A, Room 101" value={location} onChange={(e) => setLocation(e.target.value)} />
          </div>
          <div className="space-y-1 sm:col-span-2">
            <Label htmlFor="pr-comment">Comment</Label>
            <Input id="pr-comment" placeholder="Optional note" value={comment} onChange={(e) => setComment(e.target.value)} />
          </div>
        </div>
        <Button type="button" onClick={handleGenerate} disabled={!canGenerate}>
          Generate script
        </Button>
        {script && <ScriptOutput script={script} fileName="install-printer.ps1" />}
      </CardContent>
    </Card>
  );
}
