import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Trash2, AlertTriangle } from "lucide-react";
import { ScriptOutput, psQuote } from "./script-output";

function buildScript(f: {
  removeAd: boolean;
  computerName: string;
  removeDns: boolean;
  dnsZone: string;
  dnsName: string;
  dnsServer: string;
  removeDhcp: boolean;
  dhcpServer: string;
  scopeId: string;
  reservationIp: string;
  removePrinter: boolean;
  printerName: string;
}): string {
  const lines: string[] = [
    "# Remove Equipment from Network - generated by SCCC IT Reporting",
    "# Run in an elevated PowerShell (Run as Administrator).",
    "# Requires the relevant RSAT modules (ActiveDirectory / DnsServer / DhcpServer)",
    "# and rights on the domain / DNS / DHCP servers.",
    "",
    "$ErrorActionPreference = 'Continue'",
    "",
  ];

  if (f.removeAd && f.computerName) {
    lines.push(
      `# --- Remove Active Directory computer object ---`,
      `try {`,
      `    Remove-ADComputer -Identity '${psQuote(f.computerName)}' -Confirm:$false`,
      `    Write-Host "Removed AD computer object '${psQuote(f.computerName)}'." -ForegroundColor Green`,
      `} catch { Write-Host "AD removal failed: $($_.Exception.Message)" -ForegroundColor Red }`,
      "",
    );
  }

  if (f.removeDns && f.dnsZone && f.dnsName) {
    const serverArg = f.dnsServer ? ` -ComputerName '${psQuote(f.dnsServer)}'` : "";
    lines.push(
      `# --- Remove DNS A record ---`,
      `try {`,
      `    Remove-DnsServerResourceRecord -ZoneName '${psQuote(f.dnsZone)}' -Name '${psQuote(f.dnsName)}' -RRType 'A' -Force${serverArg}`,
      `    Write-Host "Removed DNS record '${psQuote(f.dnsName)}.${psQuote(f.dnsZone)}'." -ForegroundColor Green`,
      `} catch { Write-Host "DNS removal failed: $($_.Exception.Message)" -ForegroundColor Red }`,
      "",
    );
  }

  if (f.removeDhcp && f.scopeId && f.reservationIp) {
    const serverArg = f.dhcpServer ? ` -ComputerName '${psQuote(f.dhcpServer)}'` : "";
    lines.push(
      `# --- Remove DHCP reservation ---`,
      `try {`,
      `    Remove-DhcpServerv4Reservation -ScopeId '${psQuote(f.scopeId)}' -IPAddress '${psQuote(f.reservationIp)}'${serverArg}`,
      `    Write-Host "Removed DHCP reservation for '${psQuote(f.reservationIp)}'." -ForegroundColor Green`,
      `} catch { Write-Host "DHCP removal failed: $($_.Exception.Message)" -ForegroundColor Red }`,
      "",
    );
  }

  if (f.removePrinter && f.printerName) {
    lines.push(
      `# --- Remove local printer & its port ---`,
      `try {`,
      `    $printer = Get-Printer -Name '${psQuote(f.printerName)}' -ErrorAction Stop`,
      `    $port = $printer.PortName`,
      `    Remove-Printer -Name '${psQuote(f.printerName)}'`,
      `    if ($port) { Remove-PrinterPort -Name $port -ErrorAction SilentlyContinue }`,
      `    Write-Host "Removed printer '${psQuote(f.printerName)}'." -ForegroundColor Green`,
      `} catch { Write-Host "Printer removal failed: $($_.Exception.Message)" -ForegroundColor Red }`,
      "",
    );
  }

  lines.push(`Write-Host 'Done.' -ForegroundColor Cyan`, "");
  return lines.join("\n");
}

export function RemoveEquipmentTool() {
  const [removeAd, setRemoveAd] = useState(true);
  const [computerName, setComputerName] = useState("");
  const [removeDns, setRemoveDns] = useState(false);
  const [dnsZone, setDnsZone] = useState("");
  const [dnsName, setDnsName] = useState("");
  const [dnsServer, setDnsServer] = useState("");
  const [removeDhcp, setRemoveDhcp] = useState(false);
  const [dhcpServer, setDhcpServer] = useState("");
  const [scopeId, setScopeId] = useState("");
  const [reservationIp, setReservationIp] = useState("");
  const [removePrinter, setRemovePrinter] = useState(false);
  const [printerName, setPrinterName] = useState("");
  const [script, setScript] = useState<string | null>(null);

  const canGenerate =
    (removeAd && computerName.trim()) ||
    (removeDns && dnsZone.trim() && dnsName.trim()) ||
    (removeDhcp && scopeId.trim() && reservationIp.trim()) ||
    (removePrinter && printerName.trim());

  const handleGenerate = () => {
    setScript(
      buildScript({
        removeAd,
        computerName: computerName.trim(),
        removeDns,
        dnsZone: dnsZone.trim(),
        dnsName: dnsName.trim(),
        dnsServer: dnsServer.trim(),
        removeDhcp,
        dhcpServer: dhcpServer.trim(),
        scopeId: scopeId.trim(),
        reservationIp: reservationIp.trim(),
        removePrinter,
        printerName: printerName.trim(),
      }),
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Trash2 className="h-5 w-5" /> Remove equipment from the network
        </CardTitle>
        <CardDescription>
          Select what to clean up when decommissioning a device, then generate a PowerShell script.
          Each section is optional — leave the ones you don't need unchecked.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>These actions permanently remove records. Review the generated script before running it.</span>
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2">
            <Checkbox id="rm-ad" checked={removeAd} onCheckedChange={(c) => setRemoveAd(!!c)} />
            <Label htmlFor="rm-ad" className="cursor-pointer">Remove Active Directory computer object</Label>
          </div>
          {removeAd && (
            <div className="space-y-1">
              <Label htmlFor="rm-ad-name">Computer name</Label>
              <Input id="rm-ad-name" placeholder="SCCC-LT-042" value={computerName} onChange={(e) => setComputerName(e.target.value)} />
            </div>
          )}
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2">
            <Checkbox id="rm-dns" checked={removeDns} onCheckedChange={(c) => setRemoveDns(!!c)} />
            <Label htmlFor="rm-dns" className="cursor-pointer">Remove DNS A record</Label>
          </div>
          {removeDns && (
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <Label htmlFor="rm-dns-zone">DNS zone</Label>
                <Input id="rm-dns-zone" placeholder="sccc.edu" value={dnsZone} onChange={(e) => setDnsZone(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="rm-dns-name">Record name (host)</Label>
                <Input id="rm-dns-name" placeholder="scccc-lt-042" value={dnsName} onChange={(e) => setDnsName(e.target.value)} />
              </div>
              <div className="space-y-1 sm:col-span-2">
                <Label htmlFor="rm-dns-server">DNS server (optional)</Label>
                <Input id="rm-dns-server" placeholder="dc01.sccc.edu" value={dnsServer} onChange={(e) => setDnsServer(e.target.value)} />
              </div>
            </div>
          )}
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2">
            <Checkbox id="rm-dhcp" checked={removeDhcp} onCheckedChange={(c) => setRemoveDhcp(!!c)} />
            <Label htmlFor="rm-dhcp" className="cursor-pointer">Remove DHCP reservation</Label>
          </div>
          {removeDhcp && (
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <Label htmlFor="rm-dhcp-scope">Scope ID</Label>
                <Input id="rm-dhcp-scope" placeholder="10.0.5.0" value={scopeId} onChange={(e) => setScopeId(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="rm-dhcp-ip">Reserved IP address</Label>
                <Input id="rm-dhcp-ip" placeholder="10.0.5.42" value={reservationIp} onChange={(e) => setReservationIp(e.target.value)} />
              </div>
              <div className="space-y-1 sm:col-span-2">
                <Label htmlFor="rm-dhcp-server">DHCP server (optional)</Label>
                <Input id="rm-dhcp-server" placeholder="dhcp01.sccc.edu" value={dhcpServer} onChange={(e) => setDhcpServer(e.target.value)} />
              </div>
            </div>
          )}
        </div>

        <div className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2">
            <Checkbox id="rm-printer" checked={removePrinter} onCheckedChange={(c) => setRemovePrinter(!!c)} />
            <Label htmlFor="rm-printer" className="cursor-pointer">Remove local printer & port</Label>
          </div>
          {removePrinter && (
            <div className="space-y-1">
              <Label htmlFor="rm-printer-name">Printer name</Label>
              <Input id="rm-printer-name" placeholder="Front Office HP" value={printerName} onChange={(e) => setPrinterName(e.target.value)} />
            </div>
          )}
        </div>

        <Button type="button" onClick={handleGenerate} disabled={!canGenerate}>
          Generate script
        </Button>
        {script && <ScriptOutput script={script} fileName="remove-equipment.ps1" />}
      </CardContent>
    </Card>
  );
}
